### ISSUE TITLE
JSCS not running in ember test on 2.0.0

### ISSUE THREAD

**Issue by duboff** [DockYard/ember-suave#103]
We have tried adding just now (post 2.0.0 release) ember-suave to one of our apps as per Readme and the JSCS errors are not showing when ember test is run. When we downgraded to 1.2.3, everything works again. Have not been able to identify the root cause yet.

**Comment by brzpegasus** [comment]
Weird. I am not able to reproduce. What happens when you run:

```
$ ember test --filter=jscs
```

Does it report any tests at all?

**Comment by brzpegasus** [comment]
Oh, you mean the tests are shown as failing, but you don't get details of the errors, e.g. actual vs. expected?

**Comment by duboff** [comment]
No, the problem is they don't show up as failing even though I know there are some failures there.

Here's the output:
```sh
undefined
version: 1.13.15
Built project successfully. Stored in "/Users/mikhaildubov/Chattermill/cm-frontend/tmp/class-tests_dist-1NXK9Ip6.tmp".

1..0
# tests 0
# pass  0
# skip  0
# fail  0

# ok
No tests were run, please check whether any errors occurred in the page (ember test --server) and ensure that you have a test launcher (e.g. PhantomJS) enabled.
```

**Comment by brzpegasus** [comment]
Just for the sake of it, can you `rm -rf node_modules && npm cache clean && npm install`, then try again?

**Comment by duboff** [comment]
Tried that, not helping

**Comment by brzpegasus** [comment]
What's the `undefined` part in the output you pasted?

```
undefined
version: 1.13.15
Built project successfully. Stored in "/Users/mikhaildubov/Chattermill/cm-frontend/tmp/class-tests_dist-1NXK9Ip6.tmp".
```

Does that show up every time you run any `ember` command?

**Comment by brzpegasus** [comment]
Also, can you try `ember test --server` and see if there are any errors shown in the console?

**Comment by duboff** [comment]
Hi, please ignore the _undefined_ it was because of an old version of node. The output from a new one (4.2.2) does not have it but the problem persists.

`ember test --server`  runs tests, but again without JSCS.

**Comment by brzpegasus** [comment]
I just wanted to confirm no errors were shown in the browser console when you ran `ember test --server`.

**Comment by duboff** [comment]
Nope, no errors

**Comment by brzpegasus** [comment]
Okay, so the good news is, I am able to reproduce it in a brand new ember app (though, strangely enough, not in the existing app I was testing things with). I believe it has something to do with #90. The bad news is, I don't know what the actual problem is yet, but I'll get back to you when I do!

**Comment by duboff** [comment]
Thanks a lot @brzpegasus! Appreciate your patience.

What about an existing app after `rm -rf node_modules && npm cache clean && npm install?`

**Comment by brzpegasus** [comment]
#104 should fix it.

**Comment by duboff** [comment]
:100: :fireworks: :confetti_ball:

**Comment by duboff** [comment]
A new release on NPM would be highly appreciated. Thanks

**Comment by brzpegasus** [comment]
`ember-suave@2.0.1`
