### ISSUE TITLE
disallowConstOutsideModuleScope is true ... why?

### ISSUE THREAD

**Issue by jackmatt2** [DockYard/ember-suave#105]
In the latest version of ember-suave `"disallowConstOutsideModuleScope": true`, however this is not part of the [Javascript Style Guide](https://github.com/dockyard/styleguides/blob/master/engineering/javascript.md) or the [Ember Style Guide](https://github.com/dockyard/styleguides/blob/master/engineering/ember.md).  In fact quite the contrary - `cont` is used in `function` scope in multiple places in the documentation. 

Essentially I always use `const` in preference to `let` because in the vast majority of cases the local variable is in fact immutable (probably 95% of cases for me).  This gives clarity to anyone looking at my code that once the variable has been defined it will not change anymore in the defined block.

I realise I can simply override the value in `.jscsrc` but is there a good reason for `"disallowConstOutsideModuleScope": true`?

**Comment by bcardarella** [comment]
Please see https://github.com/DockYard/ember-suave/pull/77

**Comment by bcardarella** [comment]
Also, fyi `const` does not denote immutability, just reassignment.

**Comment by jackmatt2** [comment]
Ah yeah, I knew that but my bad.  Good catch.
