### ISSUE TITLE
files inside addon folder

### ISSUE THREAD

**Issue by miguelcobain** [DockYard/ember-suave#106]
Looks like files inside `addons` don't get tested,

e.g running
```bash
$ ember test -f jscs
```

doesn't run any test on any file inside the `addon` folder.

Using ember-suave 2.0.1 and ember-cli 2.3.0.

**Comment by rwjblue** [comment]
I believe this is an ember-cli bug that has been reported (linting in the addon tree is broken in 2.3.0), can you confirm and cross link the issues?

I'll try to work on this a bit today...

**Comment by miguelcobain** [comment]
X-link: https://github.com/ember-cli/ember-cli/issues/5498
