### ISSUE TITLE
implement an overrideable JSCS config in ember-suave

### ISSUE THREAD

**Issue by olivierlesnicki** [dockyard/ember-suave#12]
implement an overrideable JSCS config in ember-suave
https://github.com/ember-cli/ember-cli/issues/3948

**Comment by rwjblue** [comment]
:+1: - Will work on this soon.

**Comment by rwjblue** [comment]
I just submitted https://github.com/dockyard/ember-suave/pull/15 to resolve this.  Once @brzpegasus has had a chance to review, we will release.

**Comment by rwjblue** [comment]
Released in 0.1.7.
