### ISSUE TITLE
Redefinition of 'Object' vs Avoid accessing Ember.Object directly

### ISSUE THREAD

**Issue by rmachielse** [DockYard/ember-suave#122]
Hi guys,

I have been running my app against the current master branch of ember-suave and came across an issue. Apparently the new `disallowDirectPropertyAccess` rule is conflicting with another rule when using `Ember.Object`.

When I use `const { Object } = Ember;` I am seeing `Redefinition of 'Object'`.
When using `Ember.Object` directly I am seeing `Avoid accessing Ember.Object directly`

**Comment by rmachielse** [comment]
One way of circumventing this issue is using `EmberObject` by renaming it: 
```javascript
const { Object: EmberObject } = Ember;
```

**Comment by brzpegasus** [comment]
Yes, that is expected. The syntax you show above (renaming to `EmberObject`) is the way to do it.
