### ISSUE TITLE
alternate repo with just the preset?

### ISSUE THREAD

**Issue by Suven** [DockYard/ember-suave#126]
Hey!

I am currently creating some support-scripts which can be used around an ember-application, but are not ember-apps themselves. One example is a tool that creates screenshots via pageres of my particular ember-app.

When adding ember-suave to that veeery small cli-tool it comes with a lot of deps I really don't need. Wouldn't it make sense to publish the jscs-preset itself as standalone?

**Comment by brzpegasus** [comment]
We intend to deprecate JSCS and move to ESLint, so this will likely not be addressed. However, the plan with ESLint is that we would have a sharable config (e.g. `eslint-config-ember-suave`), which should be equivalent to having a JSCS preset.
