### ISSUE TITLE
Bug with the version 3.0.5 of jscs

### ISSUE THREAD

**Issue by GreatWizard** [DockYard/ember-suave#129]
The problem is that `jscs` is define as **^**3.0.4 in `package.json` and today there is a new patch version of `jscs`.

With the new version of `jscs` (3.0.5) there is a bump version of `cst` from 0.3.0 to 0.4.0: https://github.com/jscs-dev/node-jscs/commit/5885239955167317593c0896420651c46114b135

And now, I have this error:
```error
Cannot find module 'babel-runtime/core-js/object/keys'
Error: Cannot find module 'babel-runtime/core-js/object/keys'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/ubuntu/.../node_modules/ember-suave/node_modules/jscs/node_modules/cst/lib/Parser.js:7:13)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)
npm ERR! Test failed.  See above for more details.
```

Edit: jscs 3.0.5 means cst 0.3.0->0.4.0 means babylon 6.7.0->6.8.1 means babel-runtime 5.0.0->6.0.0...

The real problem seems that a major version for babel-runtrime becomes a patch version with jscs...

**Comment by brzpegasus** [comment]
Thanks for reporting. I'm trying to reproduce this issue by creating a new Ember app and installing `ember-suave@3.0.1`. I am not getting this error though. What steps did you take?

**Comment by brzpegasus** [comment]
FYI, I ran `npm ls babylon` on the new project and get:

```
└─┬ ember-suave@3.0.1
  ├─┬ jscs@3.0.5
  │ └─┬ cst@0.4.2
  │   └── babylon@6.8.1
```

**Comment by hzoo** [comment]
This looks like https://github.com/jscs-dev/node-jscs/issues/2278 @markelog

**Comment by markelog** [comment]
Should fixed now

**Comment by brzpegasus** [comment]
@GreatWizard Can you verify? If so, I'll close #130.

**Comment by GreatWizard** [comment]
Thanks all iss fine now :)
It's good to know what exactly is involved!

**Comment by brzpegasus** [comment]
Thanks for the input, @hzoo and @markelog!
