### ISSUE TITLE
Ember.Object destructuring

### ISSUE THREAD

**Issue by lordpixel** [DockYard/ember-suave#132]
What is the best approach for destructuring Ember.Object? dosn't doing that cause conflict with javascript's Object?

As an expample, I want to define a model:
`
import Ember from 'ember';

export default Ember.Object.extend({
  control: '',
  message: ''
});
`

ember-suave warns about object destructuring, so I must do:

`
import Ember from 'ember';

const { Object} = Ember;

export default Object.extend({
  control: '',
  message: ''
});
`
But that collides with javascript's native Object and breaks everything. Any flag to ignore that specific case? (I still want ember-suave to require object destructuring).

**Comment by alexlafroscia** [comment]
I personally handle this by doing something like this, because you're right about the conflict with the native `Object` class.

```javascript

import Ember from 'ember';

const { Object: EmberObject } = Ember;

EmberObject.create({
  ...
});
```

it's a little weird, but makes sure that there are no conflicts and still prevents you from having a bunch of `Ember.` throughout your code.

**Comment by brzpegasus** [comment]
```js
const { Object: EmberObject } = Ember;
```

is what I'd recommend as well.
