### ISSUE TITLE
Getting errors on files using decorators with latest release (4.0.0)

### ISSUE THREAD

**Issue by devinus** [DockYard/ember-suave#135]
Error: **Node expected but "Punctuator" found**

```
**Node expected but "Punctuator" found** at pods/components/color-picker/component.js :
     1 |import Ember from 'ember';
--------^
     2 |import { on } from 'ember-computed-decorators';
```

Reproducable with:

```js
import Ember from 'ember';
import computed from 'ember-computed-decorators';

export default Ember.Object.extend({
  firstName: null,
  lastName: null,

  @computed('firstName', 'lastName')
  fullName(firstName, lastName) {
    return `${firstName} ${lastName}`;
  }
});
```

Could use some help debugging, since JSCS is supposed to support decorators out of the box.

**Comment by spieker** [comment]
+1

**Comment by bendemboski** [comment]
+1

**Comment by spieker** [comment]
Forgot to post it here after googling a bit. It's an issue of CST (used by JSCS since version 3).
https://github.com/cst/cst/issues/132

I think there can't be done anything in ember-suave except for waiting until its fixed in CST

**Comment by martndemus** [comment]
Yep, we can't fix this in ember-suave 😢

**Comment by devinus** [comment]
It seems fixing this will depend on https://github.com/DockYard/ember-suave/issues/113.
