### ISSUE TITLE
any way to turn off ember-suave for third party addons?

### ISSUE THREAD

**Issue by SirZach** [DockYard/ember-suave#138]
I'm currently using `ember-paper` which doesn't follow `ember-suave` rules but I'm getting a lot of failed tests for their components. Maybe I set up something wrong.

**Comment by rwjblue** [comment]
You are getting these failures because of incorrect configuration in ember-paper.  Specifically, [this line](https://github.com/miguelcobain/ember-paper/blob/master/index.js#L142) means that the addon will always get your applications linting rules ran against it.

**Comment by SirZach** [comment]
Makes sense. Thanks for looking into it!
