### ISSUE TITLE
Distinguish between property assignment in object literal and object destructuring

### ISSUE THREAD

**Issue by brzpegasus** [dockyard/ember-suave#23]
If you have:

```javascript
const { get: get } = Ember;
```

the `requireEnhancedObjectLiterals` flags it as an error:

```
Property assignment should use enhanced object literal function. `{ propName: propName}` is not allowed. at store.js :
     3 |
     4 |//const get = Ember.get;
     5 |const { get: get } = Ember;
----------------^
```

@rwjblue Are we ok having the enhanced object literal rule cover object destructuring cases too, or should it be a new rule? If we want it to check object destructuring, we should add test cases to reflect that, and also add an exception for `get` and `set`.

**Comment by rwjblue** [comment]
The rule is correct in this case, and we are only using `{ get: get }` as a work around to the other issue with JSCS.  I personally think the rule should stay as is, and we should recommend the following for the `get`/`set` work around:

```javascript
const get = Foo.get;
const set = Foo.set;
```
