### ISSUE TITLE
Find a rule to disallow space before parentheses in object method shorthand notation

### ISSUE THREAD

**Issue by brzpegasus** [dockyard/ember-suave#29]
Fixing #27 revealed that the `disallowSpacesInFunction` rule does not address the following test case:

```javascript
let x = {
  foo () { // space before parentheses
    console.log('foo');
  }
};
```

Need to find a suitable rule for it (or make one).

**Comment by hzoo** [comment]
I think we can modify `disallowSpaceAfterObjectKeys` in JSCS to account for this. It was returning on `property.method` because of some error before.

**Comment by hzoo** [comment]
Fixed in JSCS master via https://github.com/jscs-dev/node-jscs/commit/903c389390f04860ee9c71591a2f0345a91dd965 so should be good in next release.

**Comment by brzpegasus** [comment]
@hzoo Awesome, thanks!
