### ISSUE TITLE
New Rules: port rules from dockyard/ember-suave (ES6)

### ISSUE THREAD

**Issue by hzoo** [dockyard/ember-suave#36]
We can port over some rules created by awesome folks from `dockyard/ember-suave`.

https://github.com/dockyard/ember-suave/pull/10#issuecomment-101069954

@rwjblue
> Would love to move the custom rules upstream.

----

Rules: https://github.com/dockyard/ember-suave/tree/master/lib/rules

`requireArrayDestructuring`: https://github.com/dockyard/ember-suave/commit/5db73305cfa05b4856f89db6bb4fb1480ac9a665

```js
// bad
const colors = ['red', 'green', 'blue'];
const first = colors[0];

// good
const colors = ['red', 'green', 'blue'];
const [first] = colors;
const [red, green] = colors;
const [, , blue] = colors;
```

`requireObjectDestructuring`: https://github.com/dockyard/ember-suave/commit/9b975e68f1c52aeda1848cba857b94a726e2e1a7

```js
"requireObjectDestructuring": {
  "allExcept": ["get", "set"]
}
```

```js
// bad
let foo = SomeThing.foo;
let bar = SomeThing.Baz.bar;

// good
let { foo } = SomeThing;
let { bar } = SomeThing.Baz;

let someVariableName = SomeThing.propertyWithDifferentName;

const get = SomeThing.get;
const set = SomeThing.set;
```

**Comment by hzoo** [comment]
Oops.. wrong repo!

**Comment by bcardarella** [comment]
Now I'm curious what this was meant for

**Comment by hzoo** [comment]
Sorry I was planning on adding some JSCS rules from here upstream.
