### ISSUE TITLE
Question: Use with JSHint?

### ISSUE THREAD

**Issue by alexlafroscia** [dockyard/ember-suave#44]
Do you use `ember-suave` with JSHint? Or instead of it? I started fixing some instances of `var -> let` or `var -> const` but now I'm getting all sorts of JSHint errors when running my tests.

**Comment by hzoo** [comment]
JSHint should support some es6? `"esnext": true` in options if you didn't already do that

**Comment by rwjblue** [comment]
It is also possible that your jshint version is out of date. You can get the latest by making sure you are on the latest ember-cli-qunit version and running: `rm -rf node_modules && npm cache clear && npm install`

**Comment by alexlafroscia** [comment]
@rwjblue yeah, that ended up being the problem.  I updated to the latest `ember-cli-qunit` and now those JSHint errors went away. It's not using the latest `jshint` but I guess it's using a new enough version not to conflict.
