### ISSUE TITLE
Update to JSCS 2.0

### ISSUE THREAD

**Issue by brzpegasus** [dockyard/ember-suave#49]
It's [out](https://github.com/jscs-dev/node-jscs/releases/tag/v2.0.0)!

We should remove custom rules that now exist in the latest JSCS, like [requireTemplateStrings](http://jscs.info/rule/requireTemplateStrings.html), among other things.

**Comment by danmcclain** [comment]
Does this mean `get` and `set` destructuring don't go  :boom:?

**Comment by brzpegasus** [comment]
Exactly. It'll be such a better world!

**Comment by bcardarella** [comment]
Awesome :)

**Comment by hzoo** [comment]
Finally! - I never got around to porting the other es6 rules yet though. You can use the `--esnext` option which uses `babel-jscs` under the hood. Tracking in https://github.com/jscs-dev/node-jscs/issues/1390

**Comment by brzpegasus** [comment]
@hzoo 
> I never got around to porting the other es6 rules yet though.

I've been quite busy myself, but as things die down, I can attempt a few PRs. Hopefully soon =).
