### ISSUE TITLE
No enforcement of "Always use parentheses around arguments."

### ISSUE THREAD

**Issue by SaladFork** [dockyard/ember-suave#50]
The style guide [states](https://github.com/dockyard/styleguides/blob/master/javascript.md#functions-1):
 * Always use parentheses around arguments.
```javascript
// good
[1, 2, 3].map((x) => x * x);

// bad
[1, 2, 3].map(x => x * x);
```

But this seems to not be enforced by `ember-suave`.

(cc @elbeezy)

**Comment by hzoo** [comment]
Made a rule for this in jscs http://jscs.info/rule/requireParenthesesAroundArrowParam.html

I also have a fix for rest param `...a` in the works https://github.com/jscs-dev/node-jscs/issues/1616 which should be in jscs 2.0.1
