### ISSUE TITLE
Disallow trailing comma for object destructuring

### ISSUE THREAD

**Issue by brzpegasus** [dockyard/ember-suave#57]
```js
// bad
const { foo, bar, } = baz;

// good
const { foo, bar } = baz;
```

Not sure if this is something that can be fixed in the `disallowTrailingComma` rule in JSCS given it's ES2015 syntax. Need to investigate.

**Comment by bcardarella** [comment]
The number of trailing commas I leave is disgusting

**Comment by brzpegasus** [comment]
Unacceptable =p.

**Comment by bcardarella** [comment]
![](http://img01.deviantart.net/7bca/i/2013/173/4/8/puking_rainbows_guy_in_hd_by_lemmino-d6026ug.png)

**Comment by hzoo** [comment]
I'm pretty sure we can add it to disallowTrailingComma - I'l take a look to tomorrow and make the fix if so.

**Comment by hzoo** [comment]
Ok made https://github.com/jscs-dev/node-jscs/issues/1891

**Comment by brzpegasus** [comment]
Nice, thank you!

**Comment by hzoo** [comment]
Ok merged - will try to release a patch verson soon

**Comment by hzoo** [comment]
Releasing 2.3.5 with the changes
