### ISSUE TITLE
Support for ember-cli-mocha

### ISSUE THREAD

**Issue by HeroicEric** [DockYard/ember-suave#58]
I'm trying to convert this basically new project over to mocha from qunit and I'm getting this failure for all of the .jscs-tests that are run. Everything is passing fine.

The only tests in the app are the default tests that come with generating a model.

```
ember-cli: 1.13.7
ember-cli-mocha: 0.9.2
ember-mocha: 0.8.0
ember-suave: 
```

```
ok 73 PhantomJS 1.9 - Promotion exists
not ok 74 PhantomJS 1.9 - TestLoader Failures planning-cloud/tests/unit/promotion/model-test.jscs-test: could not be loaded
    ---
        message: >
            Can't find variable: module
        stack: >
            ReferenceError: Can't find variable: module
                at http://localhost:7357/assets/planning-cloud.js:3304
                at http://localhost:7357/assets/vendor.js:157
                at tryFinally (http://localhost:7357/assets/vendor.js:37)
                at http://localhost:7357/assets/vendor.js:163
                at http://localhost:7357/assets/test-loader.js:29
                at http://localhost:7357/assets/test-loader.js:21
                at http://localhost:7357/assets/test-loader.js:40
                at http://localhost:7357/assets/test-support.js:14858
        Log: |
    ...
```

**Comment by HeroicEric** [comment]
rwjblue [12:53 PM] 
@heroiceric: you need to specify `jscsOptions` in ember-cli-build

rwjblue [12:55 PM]
```var App = new EmberApp(defaults, {
  jscsOptions: {
    testGenerator: testGenerator
  }
});

function testGenerator(relativePath, passed, errors) {
  if (errors) {
    errors = "\\n" + this.escapeErrorString(errors);
  } else {
    errors = "";
  }

  return "describe('JSCS - " + relativePath + "', function(){\n" +
    "it('should pass jscs', function() { \n" +
    "  expect(" + !!passed + ", '" + relativePath + " should pass JSCS." + errors + "').to.be.ok; \n" +
    "})});\n";
}
```

rwjblue [12:55 PM]
@heroiceric: something like ^^, once you get my bugs ironed out there, lets get this working out of the box with suave (edited)

just moving this over here to track it

**Comment by rwjblue** [comment]
:+1:

**Comment by jmejias** [comment]
@HeroicEric I implemented your fix and now I just get this even thought I fixed all my ember style issues:

AssertionError: app.js should pass JSCS.: expected false to be truthy

on most tests. I am using the default jscs file

**Comment by HeroicEric** [comment]
@jmejias That was just some code @rwjblue threw at me in slack to get me started. I haven't fixed anything yet :smile:

**Comment by SaladFork** [comment]
I was able to get it working with:
```javascript
function testGenerator(relativePath, errors) {
  if (errors) {
    errors = '\\n' + this.escapeErrorString(errors);
  } else {
    errors = '';
  }

  var expectString = relativePath + ' should pass JSCS' + errors;

  return [
    'describe("JSCS - ' + relativePath + '", function () {',
      'it("should pass jscs", function () {',
        'expect(' + !errors + ', "' + expectString + '").to.be.ok;',
      '});',
    '});'
  ].join('\n');
}
```

I also put this at the top of the file:
```javascript
/* jscs:disable disallowVar, requireEnhancedObjectLiterals */
/* jscs:disable requireTemplateStringsForConcatenation */
```

**Comment by rwjblue** [comment]
@HeroicEric - Have you had a chance to test this out?

**Comment by HeroicEric** [comment]
Have not yet but was actually planning to take a look at this later today



—————————————————————


Eric Kelly

Lead Developer @ Greenfield



@HeroicEric all over the internet

**Comment by rmachielse** [comment]
Since today I am having another problem when using mocha.
I am seeing:

```
ReferenceError: Can't find variable: QUnit at http://localhost:7357/assets/test-support.js
```
which resolves to this project's [`test-support.js#L7`](https://github.com/dockyard/ember-suave/blob/master/vendor/ember-suave/test-loader.js#L7).

I was able to fix it by changing:
```javascript
  function isJscsDisabled() { return QUnit ? QUnit.urlParams.nojscs : false; }
```
to:
```javascript
  function isJscsDisabled() { return typeof QUnit === 'undefined' ? false : QUnit.urlParams.nojscs; }
```

Does anyone else have this problem? Should I make a pull request?

**Comment by rwjblue** [comment]
@rmachielse - Yes, please send in a PR for that change (sorry I didn't catch that on review).

**Comment by ballPointPenguin** [comment]
FYI, the @SaladFork solution is working for me.
I wonder how this could be included in either this project or ember-cli-mocha such that it does the right thing when suave and mocha are both present.

**Comment by Dhaulagiri** [comment]
This [was fixed](https://github.com/kellyselden/broccoli-jscs/pull/59) in version 1.3.1 of broccoli-jscs
