### ISSUE TITLE
Prevent printing errors before test output

### ISSUE THREAD

**Issue by alexlafroscia** [dockyard/ember-suave#59]
We use Testem's ability to print test results in an XML format to allow Circle CI to parse the errors and give us some pretty test feedback.  However, I noticed today that Ember Suave errors cause this to break down, because the error gets printed before the XML output, as well as part of the output itself

```
Property assignment should use enhanced object literal function. `{ funcName: function() {} }` is not allowed. at components/load-promise.js :
    58 |   */
    59 |  promise: computed({
    60 |    get: function() {
------------^
    61 |      return this.get('_promise');
    62 |    },
....
<testsuite name="Testem Tests" tests="1080" failures="1" timestamp="Fri Aug 07 2015 20:24:57 GMT+0000 (UTC)" time="54.631">
....
```

Later on in the XML file, the Ember Suave error is also printed in the correct format, but it being printed before the test output seems to prevent it all from being parsed right.  We're already using the `--silent` flag to try to prevent this extra output; can this easily be disabled?

**Comment by brzpegasus** [comment]
Thanks for logging this. I will more likely have time to take a look towards the end of the week/weekend.

**Comment by alexlafroscia** [comment]
Awesome, thanks :)

**Comment by brzpegasus** [comment]
Long delayed reply, but did the `--silent` option help with this? I'm not sure how to prevent anything that gets logged from appearing in the XML output. In fact, you must be getting the line `BuildingBuilding.Building..Built project successfully. Stored in "/some/path/tmp/class-tests_dist-9UFtEoUl.tmp"` before the `<testsuite...>` bit too, don't you? That also gets logged before running the actual tests.

**Comment by alexlafroscia** [comment]
I have the `--silent` flag enabled already, which prevents all of `Building...` output from messing with the XML output.  It doesn't prevent the output from Suave, however.

**Comment by brzpegasus** [comment]
I just pushed a new branch: [`jscs-output`](https://github.com/dockyard/ember-suave/compare/jscs-output). Can you see if that fixes it?

**Comment by alexlafroscia** [comment]
Sorry that took so long; I checked it out and that fixed the issue! Now JSCS errors don't mess with the XML file that gets generated, and Circle CI is able to parse those errors correctly

**Comment by brzpegasus** [comment]
Awesome! I will do some cleanup to that branch before merging, but I'm glad that resolved the issue.

**Comment by alexlafroscia** [comment]
Thanks again!

**Comment by alexlafroscia** [comment]
Hey @brzpegasus, I noticed that this issue showed up in our CI again.  Did that branch make it's way into `master`? If not, is there something I could do to fix it up and get it merged in?

**Comment by brzpegasus** [comment]
Oh yeah! I should have reopened the issue to remind myself. I was going to refactor the tests to take advantage of the new logging, but that can wait. I will merge tonight!

**Comment by alexlafroscia** [comment]
Awesome, thank you!
