### ISSUE TITLE
File exclusion doesn't seem to be working

### ISSUE THREAD

**Issue by elwayman02** [dockyard/ember-suave#66]
I tried creating a .jscsrc file and adding `excludeFiles` with the path and file name, and restarting `ember server` still showed errors for that file.

**Comment by brzpegasus** [comment]
Apologies for the delay. Are you still running into issues excluding files? One thing to note is that the file paths that you specify in `excludeFiles` are relative to `app` or `tests`, so `app/router.js` won't work, but `router.js` will. For example, this will instruct JSCS to skip `app/router.js` as well as any file in `tests/helpers`:

```json
{
  "preset": "ember-suave",
  "excludeFiles": ["router.js", "helpers/**"]
}
```

**Comment by elwayman02** [comment]
What if I have an `app/helpers` folder as well? In your example, how would Ember-Suave know which to exclude?

**Comment by brzpegasus** [comment]
It would exclude both. I realize it's not very flexible, but `excludeFiles` (which is a `broccoli-jscs` option exposed by `ember-suave`) [pattern matches against the relative path](https://github.com/kellyselden/broccoli-jscs/blob/aafbdb196c108daf78e5ab4e06137919ba666285/index.js#L127) of the file, which is itself passed in from `broccoli-persistent-filter`.

**Comment by brzpegasus** [comment]
Closing this issue as `excludeFiles` is technically working, despite the limitation explained above.
