### ISSUE TITLE
performance issues on large repo :(

### ISSUE THREAD

**Issue by SSS2557** [dockyard/ember-suave#71]
Hello @rwjblue 

First want to thank a lot for putting all this together. This is pretty much a requirement for any repo :)
and its great to have the most used rules readily available while jscs is still maturing.

I am currently unable to share a repo since it is not public. However, the build times were about 30 seconds initial and 6 seconds thereafter for changes.

I tried broccoli-jscs as well as ember-suave independently and in both cases, the build times are now like 2 mins :(

successive builds are now 3, sometimes 3.5 minutes.

Any known areas where broccoli-jscs or ember-suave will needs focus at the moment? or is it like pretty much all set?

Let me know how I can help and it would be great if you could point me to the direction :)

**Comment by rwjblue** [comment]
A few initial questions:

* What node version?
* What npm version?
* What ember-cli version?
* What platform (OSX, Linux, Windows, etc)?
* What ember-suave version?
* How many total files in `app/`, and how many in `tests/`?
* How long does the broccoli-jscs tree take?
* Can you share the "slow tree" graph?

---

Random thoughts/musings:

* A bunch of work has been going into most of the build systems building blocks.  Things like broccoli-persistent-filter (which broccoli-jscs@1.1.0 utilizes) greatly reduce initial build time (when at least one build has happened before).
* Windows IO performance is *really* bad in all of node-land (hoping this isn't related).
* To take advantage of the most recent tooling system updates, you need to be using the latest ember-cli and run `rm -rf node_modules && npm cache clear && npm install` to ensure you get updated nested dependencies.
* It should be possible with the recent PR adding an `ember-suave` preset, to use `jscs`'s normal CLI system as either a pre-commit hook or just in CI to avoid rebuild performance impact during normal development.  (we should also make it possible to enable/disable JSCS a bit easier so that you could use `process.env` variables or something)

**Comment by hzoo** [comment]
Maybe it's an issue upstream in JSCS? I know babel-jscs/babel-eslint is rather slow - hopefully when we switch to CST/3.0 it will be faster in general / we can think about performance more

**Comment by rwjblue** [comment]
With the work in #70 it should be pretty easy to measure the raw JSCS times outside of an ember-cli build environment.  

In general though, the ember-cli build system should only be calculating JSCS failures on newly changed files (and not each file for every rebuild), and running JSCS on a single file (with an already setup configuration) should be pretty darn fast...

**Comment by SSS2557** [comment]
thanks a lot for the quick response :)

Did not want to do a lengthy write up until your response in case some areas fell in the "known" zone :)

Here is what we use:

version: 1.13.8
node: 0.10.38
npm: 2.13.4
os: darwin x64 (OSX)

ember-suave version: ^1.1.0

Files breakdown in app/ (843)

3 ./transforms
4 ./initializers
7 ./utils
18 ./helpers
34 ./mixins
46 ./components
52 ./serializers
56 ./adapters
57 ./controllers
73 ./routes
86 ./models
97 ./styles
103 ./views
200 ./templates
843 .

Files breakdown in tests/ (183)

17 ./helpers
24 ./integration
66 ./fixtures
69 ./unit
183 .

will share the graph in a bit

@stefanpenner has a slight bit of a context to this repo :)

When I do a jscs . on app its pretty quick, like within a second or two. When I run it for the whole repo, even with the --fix flag it takes like 3.5 seconds.

**Comment by rwjblue** [comment]
> When I do a jscs . on app its pretty quick, like within a second or two. When I run it for the whole repo, even with the --fix flag it takes like 3.5 seconds.

Right, so something is hitting a pathological case. 

Can you try the approach done in https://github.com/aptible/ember-json-schema/pull/1 (add `.jscsrc` with a preset and use that custom fork of ember-suave), and tell me the time of `jscs app` and `jscs tests`?

**Comment by SSS2557** [comment]
initial build time with 1.2.0:  

lot lesser than yesterday with 1.1.0, still a lot

Build successful - 118677ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
JSHint tests- QUnit                           | 76415ms             
LessCompiler                                  | 16571ms             
ConcatWithMaps                                | 6139ms              

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
JSHint tests- QUnit (1)                       | 76415ms             
LessCompiler (2)                              | 16705ms (8352 ms)   
ConcatWithMaps (4)                            | 9318ms (2329 ms)  

incremental with js file touch:

a lotttt lesser time compared to 1.1.0 :)  (also had a jshint error during this build, not sure how that effects this tree)

Build successful - 17974ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
ConcatWithMaps                                | 7793ms              
Babel                                         | 1954ms              
Funnel: App JS Files                          | 1823ms              
ES6: App Tree                                 | 1301ms              
JSHint app- QUnit                             | 970ms               

Slowest Trees (cumulative)                    | Total (avg)         
----------------------------------------------+---------------------
ConcatWithMaps (4)                            | 8200ms (2050 ms)    
Babel (5)                                     | 2088ms (417 ms)     
Funnel: App JS Files (1)                      | 1823ms              
ES6: App Tree (1)                             | 1301ms              
JSHint app- QUnit (1)                         | 970ms

**Comment by SSS2557** [comment]
sorry about the bad markdown :( wonder how others did it lol

**Comment by rwjblue** [comment]
JSHint is the slowest (which seems unrelated to ember-suave). Can you confirm that you are using the latest version of ember-cli-qunit?

**Comment by SSS2557** [comment]
yes, I am using 
 ember-cli-qunit@1.0.3
  └─┬ broccoli-jshint@1.1.0
    └── jshint@2.8.0 

however, there is another bug now. 
I do not see any errors shown on the first build on the incremental ones with just touching the file.

Or even once I kill the process and start the server

I think sublime text has a lot of things to do with this or probably the plugins I use with them like the sublime-linter and the jscs-formatter

**Comment by SSS2557** [comment]
ok,

I just confirmed. No, its not sublime text or any plugins.

I do a total clean first(with an npm script I use) deleting literally everything possible generated towards a build.

Then, I do an npm start, which just does an ember server.

This is the only time it runs all the checks. The build time for this looks like:

Build successful - 137642ms.

Slowest Trees                                 | Total               
----------------------------------------------+---------------------
JSHint tests- QUnit                         | 75135ms             
LessCompiler                                  | 15741ms             
Babel                                              | 11197ms             
JSHint app- QUnit                          | 7622ms              

Slowest Trees (cumulative)            | Total (avg)         
----------------------------------------------+---------------------
JSHint tests- QUnit (1)                    | 75135ms             
LessCompiler (2)                            | 15848ms (7924 ms)   
Babel (5)                                         | 15121ms (3024 ms)   
ConcatWithMaps (4)                       | 9248ms (2312 ms)    
JSHint app- QUnit (1)                      | 7622ms   

Now, when I touch a file which had errors earlier, the build is super fast, but no checks are done. I kill the server and start it again, still no checks.

I clean everything and then start, then it checks again and shows all the errors. Thats probably why the faster incremental builds. Its somehow skipping the check

**Comment by SSS2557** [comment]
should I open another issue?
