### ISSUE TITLE
Ability to dictate when style tests are run

### ISSUE THREAD

**Issue by tundal45** [dockyard/ember-suave#72]
This is part question part request. If there already is a way to configure the style tests to run before unit/acceptance tests are run, please let me know. If not, would that be something that other folks besides me want? Where in the code should I look to possibly play around building support for this?

Thanks!

**Comment by rwjblue** [comment]
Right now the tests are loaded by ember-cli-test-loader as a naive iteration of all modules that are known. It should be possible to enforce a specific order, but I don't really think this is something that ember-suave would want to do automatically.

I did submit https://github.com/ember-cli/ember-cli-test-loader/pull/17 to allow this to be done much easier in an application. Something like this (pseudo code):

```
// tests/test-helper.js
import TestLoader from 'ember-cli/test-loader';

TestLoader.prototype.listModules = function() {
  var knownModules = Object.keys(requirejs.entries);

  return knownModules.sort();
}
```

(and update with your special sorting rules)

**Comment by rwjblue** [comment]
Closing for now, let me know if I've missed anything....

**Comment by tundal45** [comment]
Thanks @rwjblue!
