### ISSUE TITLE
Push custom rules upstream to `jscs-dev/node-jscs`

### ISSUE THREAD

**Issue by seanpdoyle** [dockyard/ember-suave#78]
I've created PRs for a subset of `ember-suave`'s custom JSCS rules:

* [disallowVar](https://github.com/jscs-dev/node-jscs/pull/1983)
* [requireArrayDestructuring](https://github.com/jscs-dev/node-jscs/pull/1984)
* [requireObjectDestructuring](https://github.com/jscs-dev/node-jscs/pull/1986)
* [requireEnhancedObjectLiterals](https://github.com/jscs-dev/node-jscs/pull/1985)

As/if they get merged upstream, we should remove them from this package.

Also, how does `ember-suave`'s [requireTemplateStringsForConcatenation](https://github.com/dockyard/ember-suave/blob/master/lib/rules/require-template-strings-for-concatenation.js) from `node-jscs`'s [requireTemplateStrings](https://github.com/jscs-dev/node-jscs/blob/master/lib/rules/require-template-strings.js)?

If they're different, I'll gladly open a PR as well, I was just unsure if it was a duplicate rule.

**Comment by brzpegasus** [comment]
> As/if they get merged upstream, we should remove them from this package.

Thanks! I appreciate the effort to move these upstream. It was always the plan to do so, just lack of time.

> Also, how does ember-suave's requireTemplateStringsForConcatenation from node-jscs's requireTemplateStrings?

`ember-suave` will always force template strings, except for breaking up long statements:

```js
// not valid
let foo = 'foo' + 'bar';
let greeting = `Hello, ${name}!  ` + 'Enjoy your stay!';

// valid
let foo = 'foobar';
let greeting = `Hello, ${name}! ` +
  'Enjoy your stay!'; // ok because the string concatenation is used to break the line
```

I believe the rule in `node-jscs` will allow both those invalid cases if you select `{ "allExcept": ["stringConcatenation"] }` as an option, and will reject the 2nd valid example if you select `true` to enforce template strings all the time (need to confirm though).

**Comment by hzoo** [comment]
Great! should be able to merge this for a 2.6 release!

**Comment by seanpdoyle** [comment]
Merged:

* `requireObjectDestructuring `: https://github.com/jscs-dev/node-jscs/commit/bc6f9608c78068c089e342b4b84c7fda98fa1552
* `requireEnhancedObjectLiterals`: https://github.com/jscs-dev/node-jscs/commit/b8969d48584e169956422120d71be8f24e73f06b
* `requireArrayDestructuring`: https://github.com/jscs-dev/node-jscs/commit/ecec961417f2b1aef17fe10d2a2231c7f3d50717
* `disallowVar`: https://github.com/jscs-dev/node-jscs/commit/3c2dbf7eca2bf65b9985ff46d2c54317237c55d4

Looks like they're in the `2.6.0` milestone

**Comment by rwjblue** [comment]
@seanpdoyle - Can you submit a PR that:

* deprecates our internal versions with a message that they should use the new rules upstream (we can't remove because users could have specific overrides/usage of our rules directly)
* changes our `lib/jscsrc.json` to use the newly added rules in JSCS 2.6.0
* updates jscs to 2.6.0 

We will have to wait for merging until 2.6.0 is released, but then we can release an update...

**Comment by seanpdoyle** [comment]
@rwjblue https://github.com/dockyard/ember-suave/pull/81

They're pretty weak deprecation warnings, but they can be improved once the details are set in stone after the 2.6 release.

**Comment by seanpdoyle** [comment]
:tada:
