### ISSUE TITLE
Incorporate jscs-ember-deprecations rules.

### ISSUE THREAD

**Issue by rwjblue** [dockyard/ember-suave#82]
The rules are still being worked on, but https://github.com/minichate/jscs-ember-deprecations looks awesome.  Keeping that as a standalone library with only deprecation related rules seems like a good idea, then ember-suave can include it as a dep and enable the rules.

**Comment by rwjblue** [comment]
I am unsure how to include rules from dependencies, but I believe it should be possible (maybe @hzoo knows off cuff).

**Comment by minichate** [comment]
o/

Let me know what I can do to help! In the meantime I'll continue adding deprecation rules as my schedule permits
