### ISSUE TITLE
Editor can't find "ember-sauve" preset.

### ISSUE THREAD

**Issue by Sinled** [dockyard/ember-suave#93]
Hi, 
maybe i am missing something, but after adding preset option to ``.jscsrc``
```json
{
  "preset": "ember-suave"
}
```

Webstorm gives me a warning:
``Preset "ember-suave" does not exist``

Any ideas how can i fix this problem?

With ``ember-cli`` addon works perfectly.

**Comment by rwjblue** [comment]
Suggestions:

* ensure that webstorm is using the latest version of JSCS (often this means `npm install -g jscs` but could be different in your case)
* ensure that you are using the latest version of ember-suave in your project

**Comment by Sinled** [comment]
Oh, thanks
> ensure that webstorm is using the latest version of JSCS 
update fixed the problem.

Sorry for bothering.

**Comment by rwjblue** [comment]
Awesome, thanks for confirming!
