### ISSUE TITLE
npm test not in sync locally & first run of npm test different from following runs

### ISSUE THREAD

**Issue by amyrlam** [DockYard/ember-suave#94]
Not sure if I'm missing something when changing `.jscsrc` rules. 

I make a change to `.jscsrc` e.g. remove `"disallowVar": null`, and run a `npm test` to see what I should fix. Then fix the code. I run `npm test` locally again and get a passing test suite (Note: `not ok 1405` is an unrelated error that I'm debugging...):

```
...
ok 1401 PhantomJS 1.9 - JSCS - unit/utils: unit/utils/role-among-test.js should pass jscs
ok 1402 PhantomJS 1.9 - JSHint - unit/utils: unit/utils/role-among-test.js should pass jshint
ok 1403 PhantomJS 1.9 - roleAtLeast macro: returns false if session.user is not a user
ok 1404 PhantomJS 1.9 - roleAtLeast macro: returns false if session.user does not have the role
not ok 1405 PhantomJS - Browser "phantomjs /Users/alam/src/Tango/node_modules/ember-cli/node_modules/testem/assets/phantom.js http://localhost:7357/3320" exited unexpectedly.

1..1405
# tests 1405
# pass  1404
# fail  1
npm ERR! Test failed.  See above for more details.
```

I push my code to GitHub and the build fails on Travis. Why wasn't the local `npm test` the same? 

```
...
disallowVar: Variable declarations should use `let` or `const` not `var` at acceptance/configure/conditions/gzip-conditions-test.js :
     9 |const { merge } = Ember;
    10 |
    11 |var application;
--------^
    12 |var cacheConditionSpecificAttrs;
    13 |var contentsRouteUrl;
disallowVar: Variable declarations should use `let` or `const` not `var` at acceptance/configure/conditions/gzip-conditions-test.js :
    10 |
    11 |var application;
    12 |var cacheConditionSpecificAttrs;
--------^
    13 |var contentsRouteUrl;
    14 |var gzipRouteUrl;
disallowVar: Variable declarations should use `let` or `const` not `var` at acceptance/configure/conditions/gzip-conditions-test.js :
...
1..1466
# tests 1466
# pass  1460
# fail  6
```

Maybe related, I've noticed that when I'm changing the `.jscsrc`, the first time I run `npm test` locally, I'll get these errors at the top, before `npm test` starts going through all the numbers of tests:

```
disallowVar: Variable declarations should use `let` or `const` not `var` at acceptance/configure/conditions/gzip-conditions-test.js :
     9 |const { merge } = Ember;
    10 |
    11 |var application;
--------^
    12 |var cacheConditionSpecificAttrs;
    13 |var contentsRouteUrl;
```

**But the second or third time I run `npm test` locally after changing code to fix the rule I've edited in the `.jscsrc`, I don't get these errors at the top, it just starts with the numbered tests** e.g. 

```
npm test

> tango@0.0.0 test /Users/alam/src/Tango
> ember test

version: 1.13.12
Building[Deprecated] new this.Funnel(..) is deprecated, please use broccoli-funnel directly instead  [addon: ember-modal-dialog]
[Deprecated] new this.Funnel(..) is deprecated, please use broccoli-funnel directly instead  [addon: ember-tooltips]
Building..Warning: ignoring input sourcemap for bower_components/ember/ember-template-compiler.js because ENOENT: no such file or directory, open '/Users/alam/src/Tango/tmp/concat_with_maps-input_base_path-wN2UTJOc.tmp/0/bower_components/ember/ember-template-compiler.map'
Built project successfully. Stored in "/Users/alam/src/Tango/tmp/class-tests_dist-ELMgJtJA.tmp".
ok 1 PhantomJS 1.9 - JSCS - abilities: abilities/all.js should pass jscs
ok 2 PhantomJS 1.9 - JSHint - abilities: abilities/all.js should pass jshint
ok 3 PhantomJS 1.9 - Acceptance: account/index/2fa-disable:
  As a User with 2FA enabled, I can disable it when entering a valid
  Authentication Code
``` 

* We're applying ember-suave to an existing code base and un-null-ing all the things that we saw on first `npm test`.
* I have tried using a linter, but I'm having some unrelated problems with Atom linter and linter-jscs right now.

If you have any ideas or need more info, please let me know, thanks!

**Comment by rwjblue** [comment]
I believe that this is an issue with caching in broccoli-jscs.

Also, I would not suggest the rollout path that you are following currently.  I would suggest adding ember-suave, with its default rules then adding `// jscs:ignore` to every JS file.  As you touch a file during your normal development you can spruce it up...

**Comment by amyrlam** [comment]
Ah, ok. I was going to add that it seems like if the number of JSCS errors is high, it cuts off as well. I guess I will see if it happens once the code base is at the default `.jscsrc` and we are adding a custom rule.

That `// jscs:ignore` way makes sense, I think we are too far down this road to implement rn, but will next time.

I guess that's all for this issue then, thanks for the quick response!

**Comment by rwjblue** [comment]
We definitely do need to fix that caching issue upstream.

**Comment by amyrlam** [comment]
Not sure if I missed any context, but I made an issue to get the conversation started: https://github.com/kellyselden/broccoli-jscs/issues/53

**Comment by brzpegasus** [comment]
Closing this issue in favor of #97.
