### ISSUE TITLE
All identifiers must be camelCase or UPPER_CASE

### ISSUE THREAD

**Issue by skaterdav85** [dockyard/ember-suave#96]
Is it possible to ignore a rule in a certain file? For example, I am using Mirage and in a factory, I have a property with an underscore, like post_id. I can't really change that since that is the expected attribute from the backend.

```js
export default Mirage.Factory.extend({
  post_id: 3
});
```

**Comment by duggiefresh** [comment]
Hey, try this:

```js
export default Mirage.Factory.extend({
  post_id: 3 // jscs:ignore requireCamelCaseOrUpperCaseIdentifiers
});
```

Here's more on [error suppression](http://jscs.info/overview#error-suppression). Hope that helps

**Comment by skaterdav85** [comment]
thanks!
