### ISSUE TITLE
Alternate .jscsrc for tests

### ISSUE THREAD

**Issue by ronco** [DockYard/ember-suave#98]
Similar to how `ember-cli` provides an alternate `.jshintrc` for test files at `tests/.jshintrc` I would like to have a test file specific `tests/.jscsrc`.

The driving need in my case is working with a rails backend api that serialized data in snake_case, and the test fixtures we setup are built with corresponding snake_case object properties.  However in our main app code I want to enforce [requireCamelCaseOrUpperCaseIdentifiers](http://jscs.info/rule/requireCamelCaseOrUpperCaseIdentifiers).  I know this can be overcome in individual files with: `jscs:disable requireCamelCaseOrUpperCaseIdentifiers`, but I'd like to do it once for the whole `tests` tree.

**Comment by mmun** [comment]
An alternative is to put all your fixtures in `tests/fixtures/whatever.js` and exclude that folder with `  "excludeFiles": ["fixtures/**"]` in your .jscsrc.

Personally, I've just disabled that rule globally.

**Comment by ronco** [comment]
Thanks fo the suggestions. We're using factories with ember-cli-mirage so we have fixture generation with snake_cases overrides in line in our acceptance tests.  I could ignore those files, but I like having style enforcement on them. 

I also thought of disabling that rule altogether, but I do like enforcing that consistency in our app code. 

I've arrived at a workable solution by updating our custom acceptance test blueprint to add the disable comment line at the top of the file (and a sed script to prepend all the existing ones).
